import React from 'react'
import Head from "next/head";
import Navbar from "../components/navbar"
import Blogpost from "../components/preview-post";
import Footer from "../components/footer";



export default function Home() {

  return (
    <div>
      <Head>
        <title>Hotlarva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Blogpost/>
      <Footer theme="primary"/>
    </div>
  );
}

