import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router';
import Head from "next/head";
import Navbar from "../../components/navbar"
import Blogpost from "../../components/blog-post";
import Footer from "../../components/footer";


export default function Home() {

  const router = useRouter()

  const query = router.query

  return (
    <div>
      <Head>
        <title>Hotlarva</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar/>
        <Blogpost postId={query.pid} same={query.same}/>
      <Footer theme="primary"/>
    </div>
  );
}

